language: java
sudo: false
install: true

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TARGET_PLATFORM=e42
    - TARGET_PLATFORM=e43
    - TARGET_PLATFORM=e44
    - TARGET_PLATFORM=e45 PR_ANALYSIS=true

jdk:
  - oraclejdk7

script:
  - ./travis.sh

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
