language: java
sudo: false
install: true

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TARGET_PLATFORM=e42
    - TARGET_PLATFORM=e43
    - TARGET_PLATFORM=e44
    - TARGET_PLATFORM=e45

jdk:
  - oraclejdk7

addons:
  apt:
    packages:
    - gnome-themes-standard
    - metacity
    - libwebkit-dev

script:
  - ./travis.sh

after_failure:
 - cat /home/travis/build/SonarSource/sonar-eclipse/integrationTests/org.sonar.ide.eclipse.ui.its/target/work/data/.metadata/.log
 - cat /home/travis/build/SonarSource/sonar-eclipse/integrationTests/org.sonar.ide.eclipse.ui.its/target/surefire-reports/*

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
