language: java
sudo: false
install: true

env:
  - TARGET_PLATFORM=e37
  - TARGET_PLATFORM=e42
  - TARGET_PLATFORM=e43
  - TARGET_PLATFORM=e44
  - TARGET_PLATFORM=e45

jdk:
  - oraclejdk7

script:
  - mvn verify -B -e -V -Dtycho.disableP2Mirrors=true -Dtarget.platform=$TARGET_PLATFORM

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
