language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - mvn verify -B -e -V -Dtycho.disableP2Mirrors=true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
#
