language: java
sudo: false
install: true

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TARGET=CI
    - TARGET=IT TARGET_PLATFORM=e42
    - TARGET=IT TARGET_PLATFORM=e43
    - TARGET=IT TARGET_PLATFORM=e44
    - TARGET=IT TARGET_PLATFORM=e45
    - TARGET=IT TARGET_PLATFORM=e46

jdk:
  - oraclejdk8

script:
  - ./travis.sh

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
